# Generated by Django 4.2.4 on 2023-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
