# Generated by Django 4.2.4 on 2023-09-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
